config/routes.rb
Rails.application.routes.draw do


  get 'landing_page/index'

  get 'landing_page/photobook'

  get 'landing_page/printbook'

  get 'landing_page/slimbook'

  get 'landing_page/delivery'
  


  resources :result

  get 'result/select_an_item_1/:type_photo' => 'result#select_an_item_1'
  get 'result/select_an_item_2/:type_photo/:form' => 'result#select_an_item_2'
  get 'result/select_an_item_price/:type_photo/:form/:type_paper' => 'result#select_an_item_price'
  post 'result/calc' => 'result#calc', as: :result_calc
  post 'result/res' => 'result#res', as: :result_res
  
  
  resources :prices

  resources :order_dates

  devise_for :admins
  root 'landing_page#index'
end

app/controllers/result_controller.rb
class ResultController < ApplicationController
  
  def index

  end

	def calc
    #calc[:photo]

		#render :index
	end


  def select_an_item_1
    @price_format = Price.where("type_photo = '#{params[:type_photo]}'").select(:format).order(:format).reverse_order.distinct
    respond_to do |format|
      format.json{ render json:  @price_format}
    end
  end



  def select_an_item_2
    @price_type_paper = Price.where("type_photo = '#{params[:type_photo]}'").where("format = '#{params[:form]}'").select(:type_paper).order(:type_paper).reverse_order.distinct
    respond_to do |format|
      format.html
      format.json{ render json: @price_type_paper}
    end
  end

  def select_an_item_price
    @price_select= Price.where("type_photo = '#{params[:type_photo]}'").where("format = '#{params[:form]}'").where("type_paper = '#{params[:type_paper]}'").select(:max_num_pages, :step_pages,:min_num_pages, :price1_4, :difference1_4, :price5_99, :difference5_99)
    respond_to do |format|
      format.html
      format.json{ render json: @price = { price: @price_select }}
    end
  end

  def show
    respond_to do |format|
      format.html
      format.json{ render json:  @pric = Price.all}
       
        @pric = Price.select(:format, :type_photo).order(:format).reverse_order
    end
  end


  def res
    redirect_to result_index_path
  end



  



end

app/helpers/result_helper.rb
module ResultHelper
end

app/views/result/_calc.html.erb
<div class="bg-danger">
  <%= @input_error %><br/>
</div>

<p>Кількість розворотів: <%= @num_pages %></p>
<p>Тираж: <%= @number_copies %></p>
<p>Ціна за одиницю товару: <%= @Price_calc %></p>
<p>Ціна за весь товар: <%= @Price_all %></p>

app/views/result/index.html.erb
<% content_for :futer do %>

  <li ><a class="active_menu" href="<%= result_index_path %>">Ціни</a></li>

  <%= render 'landing_page/futer' %>
  
  <li><a class="not_active" href="<%= landing_page_photobook_path  %>">Photobook</a></li>
  <li><a class="not_active" href="<%= landing_page_printbook_path  %>">Printbook</a></li>
  <li><a class="not_active" href="<%= landing_page_slimbook_path  %>">Slimbook</a></li>
  <li><a class="not_active" href="<%= landing_page_delivery_path  %>">Доставка</a></li>
<% end %>



<div class="container">
  <div class="form_calculator ">
    <%= form_for :calc, url: result_calc_path do |f| %>

      <div class="field">
        <%= f.label "Вид фотодруку", class: "forms" %>
        <div id="calc_photo" class="row one background_calc_element center">
          <% @pric = Price.select(:type_photo).distinct %>
          <% checkeds = true %>
          <% @pric.each do |fr| %>
              <% if checkeds %>
                <input type="radio" class="calc_format checkbox_none" id="my-checkbox<%= fr.type_photo %>" name="calc[photo]" value="<%= fr.type_photo %>" checked />
                  <% checkeds = false %>
              <% else %>
                <input type="radio" class="calc_format checkbox_none" id="my-checkbox<%= fr.type_photo %>" name="calc[photo]" value="<%= fr.type_photo %>"/>
              <% end %>

              <label class="photo_label col-md-3" for="my-checkbox<%= fr.type_photo %>">
                <img class="photo_img " src="/assets/print/<%= fr.type_photo %>.jpg">
                  <%= fr.type_photo %>
              </label>
          <% end %>
        </div>
      </div>    
     
      <div class="field">
        <%= f.label "Формат", class: "forms" %>
        <div id="calc_format">
        </div>
      </div>

      <div >
        <%= f.label "Iнше", class: "forms" %>
      </div> 

      <div class="backgraund_paper_and_num">
        <div class="field field_paper">
          <div id="calc_paper">
          </div>
        </div> 
     
        <div class="field field_turns">
          <%= f.label "К-сть розворотів", class: "forms number_of_turns_label" %>
          <div id="number_field_number_of_turns">
             <%#= f.number_field :number_of_turns, in: 1.0..99.0, value: 1 %>
          </div>
        </div>

        <div class="field field_count">
          <%= f.label "Тираж", class: "forms field_number_label" %>
          <div id="number_field_number">
            <%= f.number_field :number, in: 1.0..99.0,  value: 1 %>
          </div>
        </div>
      </div>

      <div class="actions">
        <%#расчет через контроллер %>
        <%#= f.submit "Заказать", remote: true %>
        <!--<div class="btn btn-default dropdown-toggle" id="calculate_cost">Розрахувати</div>-->
      </div>

    <% end %>
    <div>
      <div id="calc">
        <%= render 'calc' %>
      </div>
    </div>
  </div> 
</div>





<!---->

app/views/result/show.html.erb
<div class="bg-danger">
  <%= @input_error %><br/>
</div>

<p>Кількість розворотів: <%= @num_pages %></p>
<p>Тираж: <%= @number_copies %></p>
<p>Ціна за одиницю товару: <%= @Price_calc %></p>
<p>Ціна за весь товар: <%= @Price_all %></p>