config/routes.rb
Rails.application.routes.draw do


  get 'landing_page/index'

  get 'landing_page/photobook'

  get 'landing_page/printbook'

  get 'landing_page/slimbook'

  get 'landing_page/delivery'
  


  resources :result

  get 'result/select_an_item_1/:type_photo' => 'result#select_an_item_1'
  get 'result/select_an_item_2/:type_photo/:form' => 'result#select_an_item_2'
  get 'result/select_an_item_price/:type_photo/:form/:type_paper' => 'result#select_an_item_price'
  post 'result/calc' => 'result#calc', as: :result_calc
  post 'result/res' => 'result#res', as: :result_res
  
  
  resources :prices

  resources :order_dates

  devise_for :admins
  root 'landing_page#index'
end

app/controllers/landing_page_controller.rb
class LandingPageController < ApplicationController
  def index
  end

  def photobook
  end

  def printbook
  end

  def slimbook
  end

  def delivery
  end

end

app/helpers/landing_page_helper.rb
module LandingPageHelper
end

app/views/landing_page/_futer.html.erb
<% if admin_signed_in? %>
	<li><a class="not_active" href="<%= prices_path %>">Таблиці</a></li>
	<li><a class="not_active" href="<%= admin_session_path  %>">Адміністрація</a></li>
<% end %>

app/views/landing_page/delivery.html.erb
<% content_for :futer do %>
  <li ><a class="not_active" href="<%= result_index_path %>">Ціни</a></li>
  <%= render 'futer' %>
  <li><a class="not_active" href="<%= landing_page_photobook_path  %>">Photobook</a></li>
  <li><a class="not_active" href="<%= landing_page_printbook_path  %>">Printbook</a></li>
  <li><a class="not_active" href="<%= landing_page_slimbook_path  %>">Slimbook</a></li>
  <li><a class="active_menu" href="<%= landing_page_delivery_path  %>">Доставка</a></li>
<% end %>

<div class="container">
	<div class="first_information">
	<h2>Доставка</h2>
		
		<img src="/assets/content_info/delivery.png" class="img-thumbnail"/>
	</div>
	<div class="last_information">
		<div class="content clearfix">
		    <div class="field field-name-body field-type-text-with-summary field-label-hidden">
		    	<div class="field-items">
		    		<div class="field-item even" property="content:encoded">
		    			<h3 class="delivery">Україна</h3>
							<p>Замовлення ви можете отримати наступним чином:</p>
							<ul class="bull_grin">
								<li><span class="grin">Самовивіз</span> — ви можете забрати замовлення самостійно в нашому <a class = "grin_links" href="https://www.google.com.ua/maps/place/%D0%93%D0%BE%D0%BB%D0%BE%D0%B2%D0%BD%D0%B0+%D0%B2%D1%83%D0%BB.,+152,+%D0%A7%D0%B5%D1%80%D0%BD%D1%96%D0%B2%D1%86%D1%96,+%D0%A7%D0%B5%D1%80%D0%BD%D1%96%D0%B2%D0%B5%D1%86%D1%8C%D0%BA%D0%B0+%D0%BE%D0%B1%D0%BB%D0%B0%D1%81%D1%82%D1%8C/@48.2667344,25.949718,19z/data=!3m1!4b1!4m2!3m1!1s0x473408d23cb3f315:0xbccdaaf1680d11ae?hl=ru">офісі у місті Чернівці</a>.</li>
								<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d663.9675507613916!2d25.949689836807412!3d48.266872325767366!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x473408d23cb3f315%3A0xbccdaaf1680d11ae!2z0JPQvtC70L7QstC90LAg0LLRg9C7LiwgMTUyLCDQp9C10YDQvdGW0LLRhtGWLCDQp9C10YDQvdGW0LLQtdGG0YzQutCwINC-0LHQu9Cw0YHRgtGM!5e0!3m2!1sru!2sua!4v1419607934666" width="100%" height="300" frameborder="0" style="border:0"></iframe>
								<li><span class="grin">Кур'єрською службою</span> — в інші міста України замовлення доставляється транспортними компаніями <a class = "grin_links" href="http://novaposhta.ua/"target="_blank">Нова Пошта</a> та <a class = "grin_links" href="http://www.mercury-express.com.ua/"target="_blank">Меркурій</a>.</li>
							</ul>

							<p>Термін доставки: від 1 до 3 робочих днів в залежності від від міста та служби доставки. Доставка здійснюється за рахунок клієнта. Мінімальна вартість доставки Нової пошти - 30 грн, службою доставки Меркурій - 20 грн.</p>

							<p> Уточнити дату доставки замовлення Ви можете на сайті обраної транспортної компанії.
							Обов'язково перевіряйте свої замовлення при отриманні в присутності представника служби доставки. Якщо Ви виявили певні ушкодження, <a class = "grin_links" href="faq#item_10">дотримуйтеся цих інструкцій</a>.</p>

							<ul class="bull_grin">
								<li><span class="grin">Укрпошта</span> —  якщо у Вашому місті немає представництва служб Нова пошта та Меркурій, доставку можемо здійснити Укрпоштою.</li>
							</ul>
							<p>При виборі Укрпошти, оплатити доставку потрібно перед відправленням замовлення в друк. Вартість доставки можна уточнити в службі підтримки.</p>
							<p>Зверніть увагу, що Ви додатково отримаєте сповіщення про статус посилки, якщо для доставки Ви обрали пошту чи кур'єрські служби.</p>

							<h3 class="delivery">Росія</h3>
							<p> Замовлення Ви можете отримати у наступний спосіб:</p>
							<ul class="bull_grin">
								<li><span class="grin">«Почта России»</span> – менш надійно, відносно дешево та довго. Відправка тиражу 25 шт. (<a class = "grin_links" href="printbook">PrintBook</a> 20x30 / 12 сторінок)  коштує близько 1900 рублів та термін доставки 21 робочий день по території Росії.</li>  
								<li><span class="grin">Комерційні служби</span> – більш надійно, швидше та трошки дорожче «Пошти Росії». Доставка в залежності від міста від 3 до 5 робочих днів та вартість доставки за аналогічний тираж складе 2400 руб.</li>
							</ul>

							<h3 class="delivery">Молдова</h3>
							<p>Замовлення Ви можете отримати у наступний спосіб:</p>
							<ul class="bull_grin">
								<li><span class="grin">Передача попутним транспортом.</span> Міста, що доступні для доставки: Ліпкани, Бричани, Єдинци, Бельци, Орхей, Кишинів. Термін доставки 1 робочий день.</li>  
								<li><span class="grin">«Нова Пошта»</span> Ви можете забрати посилку самі <a class = "grin_links" href="http://novaposhta.ua/map/index/ua">з найближчого</a> до кордону відділення Нової Пошти. Термін доставки 2-4 робочих дня.</li>

							<p>Ми готові розглядати Ваші варіанти доставки, а також підрахувати точну вартість конкретного замовлення. Для цього нам необхідно знати місто доставки, тип фотокниги(BamBook, PrintBook, PhotoBook, SlimBook), формат, кількість сторінок чи розворотів та тираж.</p> 

							<p>Ми завжди раді Вам допомогти по імейлу <a class = "grin_links" href="mailto:dluxkodak@mail.ru">dluxkodak@mail.ru</a></p>
					</div>
				</div>
			</div>  
		</div>

	</div>
	
	
</div>

app/views/landing_page/index.html.erb
<% content_for :futer do %>
  <li ><a class="not_active" href="<%= result_index_path %>">Ціни</a></li>
   <%= render 'futer' %>
  <li><a class="not_active" href="<%= landing_page_photobook_path  %>">Photobook</a></li>
  <li><a class="not_active" href="<%= landing_page_printbook_path  %>">Printbook</a></li>
  <li><a class="not_active" href="<%= landing_page_slimbook_path  %>">Slimbook</a></li>
  <li><a class="not_active" href="<%= landing_page_delivery_path  %>">Доставка</a></li>
<% end %>

    <div id="pxs_container" class="pxs_container">
      <div class="pxs_bg">
        <div class="pxs_bg1"></div>
        <div class="pxs_bg2"></div>
        <div class="pxs_bg3"></div>
      </div>
      <div class="pxs_loading">Loading images...</div>
      <div class="pxs_slider_wrapper">
        <ul class="pxs_slider">
          <li>
            <img src="/assets/1.jpg" alt="First Image" />
            <div class="container_info_landing_page">
              <div class="title_landing_page">ФОТОКНИГА PHOTOBOOK</div>
              <div class="Additional">Класика фотокниги; пластик, фотодрук, розворот на 180</div>
              <a class="href_landing_page" href="<%= landing_page_photobook_path%>">
                Детальніше.... 
              </a>
            </div>
          </li>
          <li><img src="/assets/2.jpg" alt="Second Image" />
            <div class="container_info_landing_page">
              <div class="title_landing_page">ФОТОКНИГА PRINTBOOK</div>
              <div class="Additional">Доступні фотокниги швидкі у виробництві</div>
              <a class="href_landing_page" href="<%= landing_page_printbook_path%>">
                Детальніше.... 
              </a>
            </div>
          </li>
          <li><img src="/assets/3.jpg" alt="Third Image" />
            <div class="container_info_landing_page">
              <div class="title_landing_page">ФОТОКНИГА SLIMBOOK</div>
              <div class="Additional">Зроблено за передовими технологіями виробництва фотокниг</div>
              <a class="href_landing_page" href="<%= landing_page_slimbook_path%>">
                Детальніше.... 
              </a>
            </div>
          </li>
      
        </ul>
        <div class="pxs_navigation">
          <span class="pxs_next"></span>
          <span class="pxs_prev"></span>
        </div>
        <ul class="pxs_thumbnails">
          <li><img src="/assets/thumbs/1.jpg" alt="First Image" />Photobook</li>
          <li><img src="/assets/thumbs/2.jpg" alt="Second Image" />Printbook</li>
          <li><img src="/assets/thumbs/3.jpg" alt="Third Image" />Slimbook</li>
         
        </ul>
      </div>
    </div>

    <div class="footer">
      
    </div>

    <!-- The JavaScript -->
 
        <script type="text/javascript">
      (function($) {
        $.fn.parallaxSlider = function(options) {
          var opts = $.extend({}, $.fn.parallaxSlider.defaults, options);
          return this.each(function() {
            var $pxs_container  = $(this),
            o         = $.meta ? $.extend({}, opts, $pxs_container.data()) : opts;
            
            //the main slider
            var $pxs_slider   = $('.pxs_slider',$pxs_container),
            //the elements in the slider
            $elems      = $pxs_slider.children(),
            //total number of elements
            total_elems   = $elems.length,
            //the navigation buttons
            $pxs_next   = $('.pxs_next',$pxs_container),
            $pxs_prev   = $('.pxs_prev',$pxs_container),
            //the bg images
            $pxs_bg1    = $('.pxs_bg1',$pxs_container),
            $pxs_bg2    = $('.pxs_bg2',$pxs_container),
            $pxs_bg3    = $('.pxs_bg3',$pxs_container),
            //current image
            current     = 0,
            //the thumbs container
            $pxs_thumbnails = $('.pxs_thumbnails',$pxs_container),
            //the thumbs
            $thumbs     = $pxs_thumbnails.children(),
            //the interval for the autoplay mode
            slideshow,
            //the loading image
            $pxs_loading  = $('.pxs_loading',$pxs_container),
            $pxs_slider_wrapper = $('.pxs_slider_wrapper',$pxs_container);
              
            //first preload all the images
            var loaded    = 0,
            $images   = $pxs_slider_wrapper.find('img');
              
            $images.each(function(){
              var $img  = $(this);
              $('<img/>').load(function(){
                ++loaded;
                if(loaded == total_elems*2){
                  $pxs_loading.hide();
                  $pxs_slider_wrapper.show();
                    
                  //one images width (assuming all images have the same sizes)
                  var one_image_w   = $pxs_slider.find('img:first').width();
              
                  /*
                  need to set width of the slider,
                  of each one of its elements, and of the
                  navigation buttons
                   */
                  setWidths($pxs_slider,
                  $elems,
                  total_elems,
                  $pxs_bg1,
                  $pxs_bg2,
                  $pxs_bg3,
                  one_image_w,
                  $pxs_next,
                  $pxs_prev);
              
                  /*
                    set the width of the thumbs
                    and spread them evenly
                   */
                  $pxs_thumbnails.css({
                    'width'     : one_image_w + 'px',
                    'margin-left'   : -one_image_w/2 + 'px'
                  });
                  var spaces  = one_image_w/(total_elems+1);
                  $thumbs.each(function(i){
                    var $this   = $(this);
                    var left  = spaces*(i+1) - $this.width()/2;
                    $this.css('left',left+'px');
                      
                    if(o.thumbRotation){
                      var angle   = Math.floor(Math.random()*41)-20;
                      $this.css({
                        '-moz-transform'  : 'rotate('+ angle +'deg)',
                        '-webkit-transform' : 'rotate('+ angle +'deg)',
                        'transform'     : 'rotate('+ angle +'deg)'
                      });
                    }
                    //hovering the thumbs animates them up and down
                    $this.bind('mouseenter',function(){
                      $(this).stop().animate({top:'-10px'},100);
                    }).bind('mouseleave',function(){
                      $(this).stop().animate({top:'0px'},100);
                    });
                  });
                    
                  //make the first thumb be selected
                  highlight($thumbs.eq(0));
                    
                  //slide when clicking the navigation buttons
                  $pxs_next.bind('click',function(){
                    ++current;
                    if(current >= total_elems)
                      if(o.circular)
                        current = 0;
                    else{
                      --current;
                      return false;
                    }
                    highlight($thumbs.eq(current));
                    slide(current,
                    $pxs_slider,
                    $pxs_bg3,
                    $pxs_bg2,
                    $pxs_bg1,
                    o.speed,
                    o.easing,
                    o.easingBg);
                  });
                  $pxs_prev.bind('click',function(){
                    --current;
                    if(current < 0)
                      if(o.circular)
                        current = total_elems - 1;
                    else{
                      ++current;
                      return false;
                    }
                    highlight($thumbs.eq(current));
                    slide(current,
                    $pxs_slider,
                    $pxs_bg3,
                    $pxs_bg2,
                    $pxs_bg1,
                    o.speed,
                    o.easing,
                    o.easingBg);
                  });
              
                  /*
                  clicking a thumb will slide to the respective image
                   */
                  $thumbs.bind('click',function(){
                    var $thumb  = $(this);
                    highlight($thumb);
                    //if autoplay interrupt when user clicks
                    if(o.auto)
                      clearInterval(slideshow);
                    current   = $thumb.index();
                    slide(current,
                    $pxs_slider,
                    $pxs_bg3,
                    $pxs_bg2,
                    $pxs_bg1,
                    o.speed,
                    o.easing,
                    o.easingBg);
                  });
              
                
              
                  /*
                  activate the autoplay mode if
                  that option was specified
                   */
                  if(o.auto != 0){
                    o.circular  = true;
                    slideshow = setInterval(function(){
                      $pxs_next.trigger('click');
                    },o.auto);
                  }
              
                  /*
                  when resizing the window,
                  we need to recalculate the widths of the
                  slider elements, based on the new windows width.
                  we need to slide again to the current one,
                  since the left of the slider is no longer correct
                   */
                  $(window).resize(function(){
                    w_w = $(window).width();
                    setWidths($pxs_slider,$elems,total_elems,$pxs_bg1,$pxs_bg2,$pxs_bg3,one_image_w,$pxs_next,$pxs_prev);
                    slide(current,
                    $pxs_slider,
                    $pxs_bg3,
                    $pxs_bg2,
                    $pxs_bg1,
                    1,
                    o.easing,
                    o.easingBg);
                  });

                }
              }).error(function(){
                alert('here')
              }).attr('src',$img.attr('src'));
            });
              
              
              
          });
        };
        
        //the current windows width
        var w_w       = $(window).width();
        
        var slide     = function(current,
        $pxs_slider,
        $pxs_bg3,
        $pxs_bg2,
        $pxs_bg1,
        speed,
        easing,
        easingBg){
          var slide_to  = parseInt(-w_w * current);
          $pxs_slider.stop().animate({
            left  : slide_to + 'px'
          },speed, easing);
          $pxs_bg3.stop().animate({
            left  : slide_to/2 + 'px'
          },speed, easingBg);
          $pxs_bg2.stop().animate({
            left  : slide_to/4 + 'px'
          },speed, easingBg);
          $pxs_bg1.stop().animate({
            left  : slide_to/8 + 'px'
          },speed, easingBg);
        }
        
        var highlight   = function($elem){
          $elem.siblings().removeClass('selected');
          $elem.addClass('selected');
        }
        
        var setWidths   = function($pxs_slider,
        $elems,
        total_elems,
        $pxs_bg1,
        $pxs_bg2,
        $pxs_bg3,
        one_image_w,
        $pxs_next,
        $pxs_prev){
          /*
          the width of the slider is the windows width
          times the total number of elements in the slider
           */
          var pxs_slider_w  = w_w * total_elems;
          $pxs_slider.width(pxs_slider_w + 'px');
          //each element will have a width = windows width
          $elems.width(w_w + 'px');
          /*
          we also set the width of each bg image div.
          The value is the same calculated for the pxs_slider
           */
          $pxs_bg1.width(pxs_slider_w + 'px');
          $pxs_bg2.width(pxs_slider_w + 'px');
          $pxs_bg3.width(pxs_slider_w + 'px');
          
          /*
          both the right and left of the
          navigation next and previous buttons will be:
          windowWidth/2 - imgWidth/2 + some margin (not to touch the image borders)
           */
          var position_nav  = w_w/2 - one_image_w/2 + 3;
          $pxs_next.css('right', position_nav + 'px');
          $pxs_prev.css('left', position_nav + 'px');
        }
        
        $.fn.parallaxSlider.defaults = {
          auto      : 0,  //how many seconds to periodically slide the content.
                      //If set to 0 then autoplay is turned off.
          speed     : 1000,//speed of each slide animation
          easing      : 'jswing',//easing effect for the slide animation
          easingBg    : 'jswing',//easing effect for the background animation
          circular    : true,//circular slider
          thumbRotation : true//the thumbs will be randomly rotated
        };
        //easeInOutExpo,easeInBack
      })(jQuery);
    </script>

    <script type="text/javascript">
      $(function() {
        var $pxs_container  = $('#pxs_container');
        $pxs_container.parallaxSlider();
      });
        </script>