config/routes.rb
Rails.application.routes.draw do


  get 'landing_page/index'

  get 'landing_page/photobook'

  get 'landing_page/printbook'

  get 'landing_page/slimbook'

  get 'landing_page/delivery'
  


  resources :result

  get 'result/select_an_item_1/:type_photo' => 'result#select_an_item_1'
  get 'result/select_an_item_2/:type_photo/:form' => 'result#select_an_item_2'
  get 'result/select_an_item_price/:type_photo/:form/:type_paper' => 'result#select_an_item_price'
  post 'result/calc' => 'result#calc', as: :result_calc
  post 'result/res' => 'result#res', as: :result_res
  
  
  resources :prices

  resources :order_dates

  devise_for :admins
  root 'landing_page#index'
end

app/models/price.rb
class Price < ActiveRecord::Base

def self.latest
	Price.order(:updated_at).last
end


end

# == Schema Information
#
# Table name: prices
#
#  id             :integer          not null, primary key
#  type_photo     :string(255)
#  type_paper     :string(255)
#  format         :string(255)
#  price1_4       :decimal(, )
#  difference1_4  :decimal(, )
#  price5_99      :decimal(, )
#  difference5_99 :decimal(, )
#  created_at     :datetime
#  updated_at     :datetime
#  min_num_pages  :integer
#  step_pages     :integer
#  max_num_pages  :integer

app/controllers/prices_controller.rb
class PricesController < ApplicationController
  before_action :set_price, only: [:show, :edit, :update, :destroy]

  # GET /prices
  def index
    @prices = Price.all
    @format = Format.all
    @printing_type = PrintingType.all
    @edition = Edition.all
    @edition_option = EditionOption.all
    @order_dates = OrderDate.all
  end

  # GET /prices/1
  def show
    redirect_to new_price_path
  end

  # GET /prices/new
  def new
    @order_dates = OrderDate.all#информация о дате приема заказа
    if admin_signed_in?
      @prices = Price.all.order(:type_photo)
      @price = Price.new

    else
      redirect_to prices_path
    end
  end

  # GET /prices/1/edit
  def edit
  end

  # POST /prices
  def create
    @price = Price.new(price_params)

    if @price.save
      # f = File.open(Rails.root.join('app/assets/javascripts/result.coffee.erb'), 'a')
      # f.puts(" ")
      f.close 
      redirect_to @price, notice: 'Price was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /prices/1
  def update
    if @price.update(price_params)
      redirect_to @price, notice: 'Price was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /prices/1
  def destroy
    @price.destroy
    f = File.open(Rails.root.join('app/assets/javascripts/result.coffee.erb'), 'a')
    f.puts(" ")
    f.close
    redirect_to prices_url, notice: 'Price was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_price
      @price = Price.find(params[:id])
    end

    

    # Only allow a trusted parameter "white list" through.
    def price_params
      params.require(:price).permit(:type_photo, :type_paper, :format, :min_num_pages, :max_num_pages, :step_pages, :price1_4, :difference1_4, :price5_99, :difference5_99)
    end
end

app/helpers/prices_helper.rb
module PricesHelper
end

app/views/prices/_form.html.erb
<%= form_for(@price) do |f| %>
  <% if @price.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@price.errors.count, "error") %> prohibited this price from being saved:</h2>

      <ul>
      <% @price.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field field_form_admin">
    <%= f.label :type_photo, "Вид фотодруку" %>
    <%= f.text_field :type_photo %>
  </div>
  <div class="field field_form_admin">
    <%= f.label :type_paper, "Тип паперу" %>
    <%= f.text_field :type_paper %>
  </div>
  <div class="field field_form_admin">
    <%= f.label :format, "Формат" %>
    <%= f.text_field :format %>
  </div>
  <br/>
  <div class="field field_form_admin">
    <%= f.label :min_num_pages, "Мін кількість розворотів" %>
    <%= f.number_field :min_num_pages, in: 1.0..500.0 %>
  </div>
  <div class="field field_form_admin">
    <%= f.label :max_num_pages, "Макс кількість розворотів" %>
    <%= f.number_field :max_num_pages, in: 1.0..500.0 %>
  </div>
  <div class="field field_form_admin">
    <%= f.label :step_pages, "Крок" %>
    <%= f.number_field :step_pages, in: 1.0..4.0 %>
  </div>
  <br/>
  <div class="field field_form_admin">
    <%= f.label :price1_4, "Ціна від 1 до 4 включно" %>
    <%= f.number_field :price1_4, in: 1.0..50000.0 %>
  </div>
  <div class="field field_form_admin">
    <%= f.label :price5_99, "Ціна від 5 до 99 включно" %>
    <%= f.number_field :price5_99, in: 1.0..50000.0 %>
  </div>
  <br/>
  <div class="field field_form_admin">
    <%= f.label :difference1_4, "Різниця цін від 1 до 4" %>
    <%= f.number_field :difference1_4, in: 1.0..500.0 %>
  </div>
  <div class="field field_form_admin">
    <%= f.label :difference5_99, "Різниця цін від 5 до 99" %>
    <%= f.number_field :difference5_99, in: 1.0..500.0 %>
  </div>
  <div class="actions">
    <%= f.submit "Зберегти", class: "btn dropdown-toggle sub_price" %>
  </div>
  <%= link_to 'Скасувати', new_price_path, class: "btn dropdown-toggle cancel_price" %>
<% end %>

app/views/prices/_price.html.erb
 <!--старая структура показки таблиц-->

<table class="table table-striped">
  <thead>
    <tr>
      <th colspan="4">  Вид фотодруку: <%= price.type_photo %></th>
    </tr>
    <tr>
      <th colspan="4"> Формат: <%= price.format %></th>
    </tr>
    <tr>
      <th colspan="2" class="price_up" >Ціна від 1-4</th>
      <th class="splan_width"></th>
      <th colspan="2" class="price_down">Ціна від 5-99</th>
    </tr>
    <th>к-сть розворотiв</th>
    <th><%= price.type_paper %></th>
    <th class="splan_width"></th>
    <th>к-сть розворотiв</th>
    <th><%= price.type_paper %></th>
  </thead>

   <tbody>
     <% i=price.min_num_pages %>
     <% pric1=price.price1_4 %>
     <% pric2=price.price5_99 %>
     <% while i < price.max_num_pages+1 %>
       <tr>
         <td class="center"><%= i %></td>
         <td class="center"><%= sprintf("%0.02f грн.", pric1)
%></td>
         <td class="splan_width"></td>
         <td class="center"><%= i %></td>
         <td class="center"><%= sprintf("%0.02f грн.", pric2)
%></td>
       </tr>
       <% i+=price.step_pages %>
       <% pric1+=price.difference1_4 %>
       <% pric2+=price.difference5_99 %>
     <% end %>
   </tbody>
 </table>
 <br>
 <br>


<!--новая структура показки таблиц-->
<!--потом можно переделать под себя как надо-->
 <% @printing_type.each do |printing_type| %>
  <% formats = @format.where(printing_type_id: printing_type.id) %> 
    <% formats.each do |format| %>
      <% editions = @edition.where(format_id: format.id) %>
      <% editions.each do |edition| %>
        <% edition_options = @edition_options.where(edition_id: edition.id) %>
        <% edition_options.each do |edition_option| %>
            <% pric = edition_option.price%>
            <div>Вид фотодруку: <%= printing_type.title %></div>
            <div><%= printing_type.photo %></div>
            <div>Формат: <%= pformat.title %></div>
            <div><%= format.photo %></div>
            <table>
            <thead>
              <tr>
                <th colspan="2" class="price_up" >Ціна від <%= edition.min_edition %> до <%= edition.min_edition %></th>
              </tr>
              <th>к-сть розворотiв</th>
              <th><%= edition_option.paper_option %></th>
            </thead>
            <tbody>

              <% (edition.min_pages..edition.max_pages).step(edition.step).each do |i| %>
              <tr>
                <td class="center"><%= i %></td>
                <td class="center"><%= sprintf("%0.02f грн.", pric)
                  %>
                </td>
              </tr>
                <% pric+=edition_option.difference %>
              <% end %>
            
              </tbody>
            </table>
            <br>
            <br>
            
        <% end %>

      <% end %>

    <% end %>

<% end %>

app/views/prices/edit.html.erb
<% content_for :futer do %>
  <li ><a class="not_active" href="<%= result_index_path %>">Ціни</a></li>
  <li><a class="not_active" href="<%= prices_path %>">Таблиці</a></li>
  <li><a class="active_menu" href="<%= admin_session_path  %>">Адміністрація</a></li>
  <li><a class="not_active" href="<%= landing_page_photobook_path  %>">Photobook</a></li>
  <li><a class="not_active" href="<%= landing_page_printbook_path  %>">Printbook</a></li>
  <li><a class="not_active" href="<%= landing_page_slimbook_path  %>">Slimbook</a></li>
  <li><a class="not_active" href="<%= landing_page_delivery_path  %>">Доставка</a></li>
<% end %>

<div class="container">
	<h1>Режим редагування таблиці</h1>

	<%= render 'form' %>
</div>

app/views/prices/index.html.erb
<% content_for :futer do %>
  <li ><a class="not_active" href="<%= result_index_path %>">Ціни</a></li>
  <li><a class="active_menu" href="<%= prices_path %>">Таблиці</a></li>
  <li><a class="not_active" href="<%= admin_session_path  %>">Адміністрація</a></li>
  <li><a class="not_active" href="<%= landing_page_photobook_path  %>">Photobook</a></li>
  <li><a class="not_active" href="<%= landing_page_printbook_path  %>">Printbook</a></li>
  <li><a class="not_active" href="<%= landing_page_slimbook_path  %>">Slimbook</a></li>
  <li><a class="not_active" href="<%= landing_page_delivery_path  %>">Доставка</a></li>
<% end %>

<div class="container">

  <div class="center">
    <% cache ['store_price', Price.latest] do %>
      <%= render @prices %>
    <% end %>
  </div>
 

</div>

app/views/prices/new.html.erb
<% content_for :futer do %>
  <li ><a class="not_active" href="<%= result_index_path %>">Ціни</a></li>
  <li><a class="not_active" href="<%= prices_path %>">Таблиці</a></li>
  <li><a class="active_menu" href="<%= admin_session_path  %>">Адміністрація</a></li>
  <li><a class="not_active" href="<%= landing_page_photobook_path  %>">Photobook</a></li>
  <li><a class="not_active" href="<%= landing_page_printbook_path  %>">Printbook</a></li>
  <li><a class="not_active" href="<%= landing_page_slimbook_path  %>">Slimbook</a></li>
  <li><a class="not_active" href="<%= landing_page_delivery_path  %>">Доставка</a></li>
<% end %>


<div class="container">


  <div class="editing_dashboard">

    <% @order_dates.each do |order_date| %>
      <%= order_date.info %>
      <%= order_date.date %>
      <%= link_to '', edit_order_date_path(order_date), class: "font-size-glyphicon glyphicon glyphicon-pencil" %> 
    <% end %>

  </div>

<table class="table table-hover font_table_futer">
  <thead>
    <tr>
      <th>Вид</th>
      <th>Тип паперу</th>
      <th>Формат</th>
      <th>Мін розв</th>
      <th>Макс розв</th>
      <th>Крок</th>
      <th>Ціна 1-4 </th>
      <th>Різниця</th>
      <th>Ціна 5-99 </th>
      <th>Різниця</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
  <% cache ['store', Price.latest] do %>
      <% @prices.each do |price| %>
        <% cache ['entry', price] do %>
          <tr class="color_table <%#= cycle('list_line_odd', 'list_line_even') %>"
    >
            <td><%= price.type_photo %></td>
            <td><%= price.type_paper %></td>
            <td><%= price.format %></td>
            <td><%= price.min_num_pages %></td>
            <td><%= price.max_num_pages %></td>
            <td><%= price.step_pages %></td>
            <td><%= price.price1_4 %></td>
            <td><%= price.difference1_4 %></td>
            <td><%= price.price5_99 %></td>
            <td><%= price.difference5_99 %></td>
            <td><%= link_to '',edit_price_path(price), class: "font-size-glyphicon glyphicon glyphicon-pencil" %></td>
            <td><%= link_to '', price, method: :delete, data: { confirm: 'Are you sure?'  }, class: "font-size-glyphicon icon-trash" %></td>
          </tr>
         <% end %> 
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= render 'form' %>
</div>

app/views/prices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type photo:</strong>
  <%= @price.type_photo %>
</p>

<p>
  <strong>Type paper:</strong>
  <%= @price.type_paper %>
</p>

<p>
  <strong>Format:</strong>
  <%= @price.format %>
</p>

<p>
  <strong>Price1 4:</strong>
  <%= @price.price1_4 %>
</p>

<p>
  <strong>Difference1 4:</strong>
  <%= @price.difference1_4 %>
</p>

<p>
  <strong>Price5 99:</strong>
  <%= @price.price5_99 %>
</p>

<p>
  <strong>Difference5 99:</strong>
  <%= @price.difference5_99 %>
</p>

<%= link_to 'Edit', edit_price_path(@price) %> |
<%= link_to 'Back', prices_path %>