config/routes.rb
Rails.application.routes.draw do


  get 'landing_page/index'

  get 'landing_page/photobook'

  get 'landing_page/printbook'

  get 'landing_page/slimbook'

  get 'landing_page/delivery'
  


  resources :result

  get 'result/select_an_item_1/:type_photo' => 'result#select_an_item_1'
  get 'result/select_an_item_2/:type_photo/:form' => 'result#select_an_item_2'
  get 'result/select_an_item_price/:type_photo/:form/:type_paper' => 'result#select_an_item_price'
  post 'result/calc' => 'result#calc', as: :result_calc
  post 'result/res' => 'result#res', as: :result_res
  
  
  resources :prices

  resources :order_dates

  devise_for :admins
  root 'landing_page#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PhotoCalc</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application'%>
  <%= csrf_meta_tags %>
  	
</head>
<body>

	<div class="navbar_container">
		<% #futer %>
		<nav class="navbar navbar-default" role="navigation">
		  <div class="container-fluid">
		    <!-- Brand and toggle get grouped for better mobile display -->
		    <div class="navbar-header">
		      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
		            <span class="sr-only">Toggle navigation</span>
		            <span class="icon-bar"></span>
		            <span class="icon-bar"></span>
		            <span class="icon-bar"></span>
		          </button>
		      
		    </div>

		    <!-- Collect the nav links, forms, and other content for toggling -->
		    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		    	<a class="navbar-brand style_brand" onClick="document.location='<%= landing_page_index_path%>'">Kodak</a>
		      <ul class="nav navbar-nav">

		      	<%= yield :futer %>

		        <li>
		       		<% if admin_signed_in? %>
	 					<%= link_to " Вихід", destroy_admin_session_path, :method => :delete, :class  => "glyphicon glyphicon-repeat exit_admin", :data => "dropdown" %>
	 				<% end %>
	 			</li>

		        <li class="dropdown">
		      </ul>
		      
		    </div><!-- /.navbar-collapse -->
		     
		  </div><!-- /.container-fluid -->
		</nav>
	</div>
	<!--futer-->

		<%= yield %>
	<% unless admin_signed_in? %>
 	<%= render partial: 'order_dates/order_date', collection: OrderDate.all %>
 	<% end %>

	<div class="heder">
		<div class="heder_level_1">
			<div class="contact" >
				<span>Контактна інформація</span>
				<div class="center_block">
					<div class="contact_info">
						E-mail:
					</div>

					<div class="contact_one">
						dluxkodak@mail.ru
						<div>bookfotoprint@mail.ru</div>
					</div>

					<div class="contact_info">Контактний телефон:
					</div>
					<div class="contact_one">
						067 372 09 86
						<div>050 374 00 70</div>
					</div>


					<div class="contact_info">Адреса:</div>
					<div class="contact_one"> Головна, 152</div>
				</div>
			</div>
			
		</div>
	</div>
	<div class="heder_level_2">
		© <%= Time.new.year %> aKodac.
	</div>


</body>
</html>